value: wsc__ws raw_value wsc__ws
?raw_value: object
        | array
        | string
        | number
        | literal

!literal: "true" | "false" | "null"

array: "[" [value_list] wsc__ws "]"
value_list: value ("," value)*

object: "{" [member_list] wsc__ws "}"
member_list: member ("," member)*
member: key ":" value
key : wsc__ws string wsc__ws

number : SIGNED_NUMBER
string : ESCAPED_STRING

%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER

%import .wsc.ws -> wsc__ws
